- name: set root password
  hosts: all
  roles:
    - juniper.junos
  connection: local
  gather_facts: no
  serial: 1

  vars:
    ansible_python_interpreter: "/Users/charlea.fleming/Desktop/py-venv/set-root-password/bin/python3"
    ansible_public_key: "{{ lookup('file', '/Users/charlea.fleming/Desktop/py-venv/set-root-password/id_rsa.pub') }}"
  vars_prompt:
    - name: "USER"
      prompt: "username"
      private: no
    - name: "PASSWD"
      prompt: "password"
      private: yes
  tasks:
    - name: set root password
      juniper_junos_config:
        host: "{{ ansible_host }}"
        port: "22"
        user: "{{ USER }}"
        passwd: "{{ PASSWD }}"
        load: set
        lines:
          - "set system root-authentication encrypted-password $6$"
        format: text
        check: true
        commit: true
      register: response
    - name: commit compare
      debug:
        var: response
