- name: gather junos facts
  hosts: all
  roles:
    - juniper.junos
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "/Users/charlea.fleming/Desktop/py-venv/set-root-password/bin/python3"
    ansible_public_key: "{{ lookup('file', '/Users/charlea.fleming/Desktop/py-venv/set-root-password/id_rsa.pub') }}"
  vars_prompt:
    - name: "USER"
      prompt: "username"
      private: no
    - name: "PASSWD"
      prompt: "password"
      private: yes
  tasks:
    - name: show encrypted password
      juniper_junos_config:
        host: "{{ ansible_host }}"
        port: "22"
        user: "{{ USER }}"
        passwd: "{{ PASSWD }}"
        load: set
        lines:
          - "show system services ssh"
        format: text
      register: crypt_pass
    - name: show password
      debug:
        var: crypt_pass