- name: deny root login via ssh
  hosts: all
  serial: 1
  gather_facts: no
  connection: local
  roles:
    - juniper.junos
  vars:
    ansible_python_interpreter: "/Users/charlea.fleming/Desktop/py-venv/version-testing/ansible/bin/python3"
    ansible_public_key: "{{ lookup('file', '/Users/charlea.fleming/Desktop/py-venv/version-testing/ansible/id_rsa.pub') }}"
  vars_prompt:
    - name: USER
      prompt: "username"
      private: no
    - name: PASSWD
      prompt: "password"
      private: yes
  tasks:
    - name: root login deny
      juniper_junos_config:
        host: "{{ ansible_host_remove_root_ssh }}"
        port: "22"
        user: "{{ USER }}"
        passwd: "{{ PASSWD }}"
        timeout: "300"
        load: set
        lines:
          - "set system services ssh root-login deny"
        format: text
        check: true
        commit: true
      register: response
    - name: commit compare
      debug:
        var: response